const express = require("express");
const superAdmin = require("../controllers/superAdmin.controller");
const auth = require("../middlewares/auth.middleware");
const user = require("../models/user.model");
const router = express.Router();
router.use(auth.protect, (auth.authorize)(user.UserRole.SUPER_ADMIN));
router.get("/stats", superAdmin.getGlobalStats);
router.get("/hospitals/pending", superAdmin.getPendingHospitals);
router.get("/hospitals/approved", superAdmin.getApprovedHospitals);
router.post("/hospitals/approve", superAdmin.approveHospital);
router.delete("/hospitals/:hospitalId", superAdmin.removeHospital);
router.post("/hospitals/ban", superAdmin.banHospital);
router.get("/doctors/pending", superAdmin.getPendingDoctorsGlobal);
router.get("/doctors/approved", superAdmin.getApprovedDoctorsGlobal);
router.post("/doctors/approve", superAdmin.approveDoctorGlobal);
router.delete("/doctors/:doctorId", superAdmin.removeDoctor);
router.post("/doctors/ban", superAdmin.banUser);
router.post("/appointments/cancel", superAdmin.cancelAppointmentGlobal);
router.get("/doctors/fees/pending", superAdmin.getPendingFeeUpdates);
router.post("/doctors/fees/approve", superAdmin.approveFeeUpdate);
router.post("/doctors/fees/bulk-request", superAdmin.bulkUpdateFees);
module.exports = router;
